package fr.ganfra.realm;

import io.realm.RealmObject;

/* DO NOT EDIT | Generated by dbgenerator */

public class Dog extends RealmObject {

    public interface Attributes {
        String AGE = "age";
        String NAME = "name";
    }

    public interface Relationships {
        String OWNER = "owner";
    }

    private short age;
    private String name;
    private Person owner;

    public short getAge() {
        return age;
    }

    public void setAge(final short age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public Person getOwner() {
        return owner;
    }

    public void setOwner(final Person owner) {
        this.owner = owner;
    }
}
